import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";

const CaskaydiaMonoNerdFontMono = LocalFont({
  src: "./fonts/CaskaydiaMonoNerdFontMono-Regular.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={CaskaydiaMonoNerdFontMono.className}>{children}</body>
    </html>
  );
}
